CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL, name TEXT NOT NULL DEFAULT '', role TEXT NOT NULL DEFAULT 'MEMBER' CHECK (role IN ('OWNER','ADMIN','MEMBER','UPLOADER','VIEWER')),
  status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','blocked')), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS sessions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), revoked_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS password_reset_tokens (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, used_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS projects (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','archived')), created_by UUID NOT NULL REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS members (project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, role TEXT NOT NULL DEFAULT 'VIEWER' CHECK(role IN ('OWNER','ADMIN','MEMBER','UPLOADER','VIEWER')), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY(project_id,user_id));
CREATE TABLE IF NOT EXISTS invitations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE, email TEXT, role TEXT NOT NULL DEFAULT 'VIEWER' CHECK(role IN ('ADMIN','MEMBER','UPLOADER','VIEWER')), token_hash TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, accepted_at TIMESTAMPTZ, created_by UUID NOT NULL REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS conversations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE, name TEXT NOT NULL DEFAULT 'General', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS conversation_members (conversation_id UUID REFERENCES conversations(id) ON DELETE CASCADE, user_id UUID REFERENCES users(id) ON DELETE CASCADE, PRIMARY KEY(conversation_id,user_id));
CREATE TABLE IF NOT EXISTS messages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES users(id), body TEXT NOT NULL CHECK(length(body) BETWEEN 1 AND 20000), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS folders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE, parent_id UUID REFERENCES folders(id) ON DELETE CASCADE, name TEXT NOT NULL, created_by UUID NOT NULL REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS files (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE, folder_id UUID REFERENCES folders(id) ON DELETE SET NULL, owner_id UUID NOT NULL REFERENCES users(id), object_key TEXT NOT NULL UNIQUE, filename TEXT NOT NULL, content_type TEXT NOT NULL, size_bytes BIGINT NOT NULL CHECK(size_bytes>0), status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','ready','deleted','trashed')), etag TEXT, is_favorite BOOLEAN NOT NULL DEFAULT false, tags TEXT[] NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS multipart_uploads (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), file_id UUID REFERENCES files(id) ON DELETE CASCADE, project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE, owner_id UUID NOT NULL REFERENCES users(id), object_key TEXT NOT NULL UNIQUE, multipart_upload_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'uploading' CHECK(status IN ('uploading','completed','aborted','expired')), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), completed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS multipart_parts (upload_id UUID NOT NULL REFERENCES multipart_uploads(id) ON DELETE CASCADE, part_number INT NOT NULL CHECK(part_number BETWEEN 1 AND 10000), etag TEXT NOT NULL, size_bytes BIGINT NOT NULL CHECK(size_bytes>0), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY(upload_id,part_number));
CREATE TABLE IF NOT EXISTS shares (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), file_id UUID NOT NULL REFERENCES files(id) ON DELETE CASCADE, created_by UUID NOT NULL REFERENCES users(id), mode TEXT NOT NULL DEFAULT 'VIEW_DOWNLOAD' CHECK(mode IN ('VIEW','DOWNLOAD','UPLOAD','VIEW_DOWNLOAD')), token_hash TEXT NOT NULL UNIQUE, password_hash TEXT, expires_at TIMESTAMPTZ, max_accesses INTEGER, access_count INTEGER NOT NULL DEFAULT 0, revoked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_events (id BIGSERIAL PRIMARY KEY, actor_id UUID REFERENCES users(id) ON DELETE SET NULL, action TEXT NOT NULL, resource_type TEXT NOT NULL, resource_id TEXT, ip TEXT, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS agent_jobs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), owner_id UUID REFERENCES users(id), project_id UUID REFERENCES projects(id), file_id UUID REFERENCES files(id), repository TEXT, action TEXT NOT NULL CHECK(action IN ('AUDIT','REPAIR','TEST','PREVIEW','PRODUCTION')), status TEXT NOT NULL DEFAULT 'QUEUED' CHECK(status IN ('QUEUED','ANALYZING','BUILDING','TESTING','REPAIRING','DEPLOYING','READY','FAILED','BLOCKED')), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS agent_job_logs (id BIGSERIAL PRIMARY KEY, job_id UUID REFERENCES agent_jobs(id) ON DELETE CASCADE, level TEXT NOT NULL, message TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS agent_artifacts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), job_id UUID REFERENCES agent_jobs(id) ON DELETE CASCADE, file_id UUID REFERENCES files(id), name TEXT NOT NULL, object_key TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS agent_builds (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), job_id UUID REFERENCES agent_jobs(id) ON DELETE CASCADE, status TEXT NOT NULL, commit_sha TEXT, logs TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS agent_repositories (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), owner_id UUID REFERENCES users(id), provider TEXT NOT NULL CHECK(provider IN ('GITHUB','VERCEL','RENDER')), repository TEXT NOT NULL UNIQUE, allow_audit BOOLEAN NOT NULL DEFAULT false, allow_repair BOOLEAN NOT NULL DEFAULT false, allow_preview BOOLEAN NOT NULL DEFAULT false, allow_production BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS agent_deployments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), job_id UUID REFERENCES agent_jobs(id), provider TEXT NOT NULL CHECK(provider IN ('GITHUB','VERCEL','RENDER')), environment TEXT NOT NULL CHECK(environment IN ('PREVIEW','PRODUCTION')), url TEXT, status TEXT NOT NULL, approved_by UUID REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now());

-- Idempotent migration from the superseded lowercase editor model. Existing installations
-- must run these statements before the CHECK constraints are tightened in a migration tool.
UPDATE users SET role=upper(role) WHERE role IN ('admin','member');
UPDATE members SET role=CASE lower(role) WHEN 'owner' THEN 'OWNER' WHEN 'editor' THEN 'MEMBER' WHEN 'uploader' THEN 'UPLOADER' ELSE 'VIEWER' END WHERE role NOT IN ('OWNER','ADMIN','MEMBER','UPLOADER','VIEWER');
UPDATE invitations SET role=CASE lower(role) WHEN 'editor' THEN 'MEMBER' WHEN 'uploader' THEN 'UPLOADER' ELSE 'VIEWER' END WHERE role NOT IN ('ADMIN','MEMBER','UPLOADER','VIEWER');

CREATE INDEX IF NOT EXISTS members_user_idx ON members(user_id); CREATE INDEX IF NOT EXISTS audit_created_idx ON audit_events(created_at DESC); CREATE INDEX IF NOT EXISTS files_search_idx ON files(project_id,filename); CREATE INDEX IF NOT EXISTS agent_jobs_owner_idx ON agent_jobs(owner_id,created_at DESC);
