import { Form, redirect, useLoaderData } from "react-router";
import type { Project, User, VaultFile } from "../../workers/item-store";

type AppContext = { cloudflare: { env: { ITEMS: DurableObjectNamespace<import("../../workers/item-store").ItemStore> }; user?: User | null } };
function store(context:AppContext){const ns=context.cloudflare.env.ITEMS;return ns.get(ns.idFromName("hub"));}
export async function loader({context}:{context:AppContext}){const user=context.cloudflare.user;if(!user||user.role!=="COLLABORATOR")throw redirect("/auth");const projects:Project[]=await store(context).listProjectsForUser(user);const files:VaultFile[]=(await Promise.all(projects.map((p:Project)=>store(context).listFiles(p.id)))).flat();return {user,projects,files};}
export async function action({request}:{request:Request}){const form=await request.formData();if(String(form.get("intent"))!=="logout")return {ok:false};const upstream=await fetch(new URL("/api/auth/logout",request.url),{method:"POST",headers:{cookie:request.headers.get("cookie")||""}});const headers=new Headers(),setCookie=upstream.headers.get("set-cookie");if(setCookie)headers.set("set-cookie",setCookie);throw redirect("/auth",{headers});}
export function meta(){return [{title:"TAIKO PRIVATE HUB · Mi panel"}];}
export default function UserPanel(){const {user,projects,files}=useLoaderData<typeof loader>();return <main className="min-h-svh bg-[#061321] p-6 text-white"><div className="mx-auto max-w-6xl"><header className="mb-8 flex items-center justify-between border-b border-slate-800 pb-5"><div><p className="text-xs uppercase tracking-widest text-blue-300">TAIKO PRIVATE HUB</p><h1 className="mt-2 text-3xl font-semibold">Panel Usuario / Colaborador</h1><p className="text-sm text-slate-400">{user.name} · {user.email}</p></div><Form method="post"><input type="hidden" name="intent" value="logout"/><button className="rounded-lg border border-slate-700 px-4 py-2 text-sm">Cerrar sesión</button></Form></header><section className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-[#0b1b2b] p-5"><h2 className="font-semibold">Mis proyectos</h2><div className="mt-4 grid gap-3">{projects.map((p:Project)=><article key={p.id} className="rounded-xl border border-slate-800 p-4"><strong>{p.name}</strong><p className="mt-1 text-sm text-slate-400">{p.description||"Sin descripción"}</p></article>)}{!projects.length&&<p className="text-sm text-slate-500">No tienes proyectos asignados.</p>}</div></div><div className="rounded-2xl border border-slate-800 bg-[#0b1b2b] p-5"><h2 className="font-semibold">Mis archivos</h2><div className="mt-4 grid gap-2">{files.slice(0,20).map((f:VaultFile)=><div key={f.id} className="rounded-lg border border-slate-800 p-3 text-sm">{f.name}</div>)}{!files.length&&<p className="text-sm text-slate-500">No hay archivos disponibles.</p>}</div></div></section></div></main>;}
