import { createRequestHandler } from "react-router";
import bcrypt from "bcryptjs";
import type { CamelAiBinding } from "./camelai-binding";
import { randomToken,type ItemStore,type User,type AiProvider } from "./item-store";
export { ItemStore } from "./item-store";
interface Env { ASSETS?:{fetch(request:Request):Promise<Response>|Response};CAMELAI?:CamelAiBinding;ITEMS:DurableObjectNamespace<ItemStore>;TAIKO_AI_API_KEY?:string;[key:string]:unknown; }
declare module "react-router"{export interface AppLoadContext{cloudflare:{env:Env;ctx:ExecutionContext;user:User|null}}}
const requestHandler=createRequestHandler(()=>import("virtual:react-router/server-build"),import.meta.env.MODE);
const OWNER_EMAIL="tramiteshbc@gmail.com",COOKIE="taiko_session",SESSION_DAYS=30;
function json(data:unknown,status=200,headers:HeadersInit={}){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json;charset=utf-8","cache-control":"no-store",...headers}})}
function shouldServeAsset(r:Request){const m=r.method.toUpperCase(),p=new URL(r.url).pathname;return (m==="GET"||m==="HEAD")&&(p.startsWith("/assets/")||p.includes(".")||p==="/robots.txt")}
function cookieValue(r:Request,n:string){for(const part of (r.headers.get("cookie")||"").split(";")){const[k,...v]=part.trim().split("=");if(k===n)return decodeURIComponent(v.join("="))}return ""}
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function sessionCookie(t:string,maxAge=SESSION_DAYS*86400){return `${COOKIE}=${encodeURIComponent(t)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}
function clearCookie(){return `${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`}
async function currentUser(r:Request,h:DurableObjectStub<ItemStore>){const t=cookieValue(r,COOKIE);return t?await h.getUserBySession(await sha256(t)):null}
async function newSession(h:DurableObjectStub<ItemStore>,id:number){const t=randomToken(32);await h.createSession(id,await sha256(t),new Date(Date.now()+SESSION_DAYS*86400000).toISOString());return t}
function safeUser(u:User){return{id:u.id,email:u.email,name:u.name,role:u.role}}
function wantsHtml(r:Request){return(r.headers.get("accept")||"").includes("text/html")}
async function readBody(r:Request):Promise<Record<string,unknown>>{const ct=(r.headers.get("content-type")||"").toLowerCase();if(ct.includes("application/json"))return await r.json().catch(()=>({})) as Record<string,unknown>;if(ct.includes("form")){const f=await r.formData();return Object.fromEntries(f.entries())}return{}}
function authSuccess(r:Request,u:User,t:string,status=200){const headers={"set-cookie":sessionCookie(t)},dest=u.role==="OWNER"?"/":"/user";return wantsHtml(r)?new Response(null,{status:303,headers:{...headers,location:new URL(dest,r.url).toString()}}):json({user:safeUser(u),redirect:dest},status,headers)}
function authFailure(r:Request,e:string,status:number){if(wantsHtml(r)){const u=new URL("/auth",r.url);u.searchParams.set("error",e);return Response.redirect(u,303)}return json({error:e},status)}
function envSecret(env:Env,name:string){const value=env[name];return typeof value==="string"?value.trim():""}
function providerEndpoint(p:AiProvider){const base=p.baseUrl.replace(/\/+$/,"");return /\/chat\/completions$/i.test(base)?base:`${base}/chat/completions`}
async function executeAgent(provider:AiProvider,apiKey:string,input:string){const response=await fetch(providerEndpoint(provider),{method:"POST",headers:{"content-type":"application/json","authorization":`Bearer ${apiKey}`},body:JSON.stringify({model:provider.model,messages:[{role:"system",content:"Eres Agente TAIKO. Responde de forma precisa, profesional y orientada a ejecutar la tarea solicitada."},{role:"user",content:input}]})});const text=await response.text();if(!response.ok)throw new Error(`provider_http_${response.status}:${text.slice(0,500)}`);let data:unknown;try{data=JSON.parse(text)}catch{throw new Error("provider_invalid_json")};const d=data as {choices?:Array<{message?:{content?:unknown}}>};const content=d.choices?.[0]?.message?.content;if(typeof content!=="string"||!content.trim())throw new Error("provider_empty_response");return content.trim()}
async function api(request:Request,env:Env):Promise<Response>{const url=new URL(request.url),parts=url.pathname.replace(/^\/api\/?/,"").split("/").filter(Boolean),hub=env.ITEMS.get(env.ITEMS.idFromName("hub")),body=()=>readBody(request);
 if(parts[0]==="auth"){
  if(parts[1]==="owner-register"&&request.method==="POST"){const b=await body(),email=String(b.email||"").trim().toLowerCase(),name=String(b.name||"").trim(),password=String(b.password||"");if(email!==OWNER_EMAIL)return authFailure(request,"owner_email_not_allowed",403);if(!name||password.length<12||password.length>128)return authFailure(request,"invalid_registration_data",400);try{const u=await hub.registerOwner(email,name,await bcrypt.hash(password,12)),t=await newSession(hub,u.id);return authSuccess(request,u,t,201)}catch(e){return authFailure(request,e instanceof Error?e.message:"registration_failed",409)}}
  if(parts[1]==="invite-register"&&request.method==="POST"){const b=await body(),inviteToken=String(b.inviteToken||""),email=String(b.email||"").trim().toLowerCase(),name=String(b.name||"").trim(),password=String(b.password||"");if(!inviteToken||!email||!name||password.length<12||password.length>128)return authFailure(request,"invalid_registration_data",400);try{const u=await hub.registerInvitedUser(inviteToken,email,name,await bcrypt.hash(password,12)),t=await newSession(hub,u.id);return authSuccess(request,u,t,201)}catch(e){return authFailure(request,e instanceof Error?e.message:"registration_failed",409)}}
  if(parts[1]==="login"&&request.method==="POST"){const b=await body(),account=await hub.getUserByEmail(String(b.email||"").trim().toLowerCase()),password=String(b.password||"");if(!account||!(await bcrypt.compare(password,account.passwordHash)))return authFailure(request,"invalid_credentials",401);return authSuccess(request,account,await newSession(hub,account.id))}
  if(parts[1]==="logout"&&request.method==="POST"){const t=cookieValue(request,COOKIE);if(t)await hub.deleteSession(await sha256(t));const headers={"set-cookie":clearCookie()};return wantsHtml(request)?new Response(null,{status:303,headers:{...headers,location:new URL("/auth",request.url).toString()}}):json({ok:true},200,headers)}
  if(parts[1]==="me"&&request.method==="GET"){const u=await currentUser(request,hub);return u?json({user:safeUser(u),memberships:await hub.listMemberships(u.id)}):json({error:"authentication_required"},401)}
  return json({error:"unknown_auth_endpoint"},404)
 }
 const user=await currentUser(request,hub);if(!user)return json({error:"authentication_required"},401);
 if(parts[0]==="projects"&&request.method==="GET")return json({projects:await hub.listProjectsForUser(user)});
 if(parts[0]==="invites"){if(user.role!=="OWNER")return json({error:"owner_required"},403);if(request.method==="GET")return json({invites:await hub.listInvites()});if(request.method==="POST"){const b=await body(),projectId=Number(b.projectId);if(!Number.isInteger(projectId)||!await hub.getProject(projectId))return json({error:"invalid_project"},400);return json({invite:await hub.createInvite(projectId,String(b.label||"Colaborador"),randomToken())},201)}}
 if(parts[0]==="ai-providers"){if(user.role!=="OWNER")return json({error:"owner_required"},403);if(request.method==="GET")return json({providers:await hub.listAiProviders()});if(request.method==="POST"){const b=await body(),name=String(b.name||"").trim(),baseUrl=String(b.baseUrl||"").trim(),model=String(b.model||"").trim(),apiKeyEnv=String(b.apiKeyEnv||"TAIKO_AI_API_KEY").trim();if(!name||!/^https:\/\//i.test(baseUrl)||!model||!/^[A-Z][A-Z0-9_]*$/.test(apiKeyEnv))return json({error:"invalid_provider_configuration"},400);return json({provider:await hub.upsertAiProvider(name,baseUrl,model,apiKeyEnv)},201)}}
 if(parts[0]==="agent-jobs"){if(user.role!=="OWNER")return json({error:"owner_required"},403);if(request.method==="GET"){const provider=await hub.getActiveAiProvider();return json({jobs:await hub.listAgentJobs(),execution:provider?"configured":"waiting_for_provider",provider:provider?{name:provider.name,model:provider.model,apiKeyEnv:provider.apiKeyEnv}:null})}if(request.method==="POST"){const b=await body(),projectId=b.projectId==null||b.projectId===""?null:Number(b.projectId),input=String(b.input||b.prompt||b.command||"").trim();if(!input)return json({error:"agent_input_required"},400);if(projectId!==null&&(!Number.isInteger(projectId)||!await hub.getProject(projectId)))return json({error:"invalid_project"},400);const provider=await hub.getActiveAiProvider();if(!provider)return json({error:"ai_provider_not_configured"},503);const key=envSecret(env,provider.apiKeyEnv);if(!key)return json({error:"ai_provider_secret_not_configured",secret:provider.apiKeyEnv},503);const job=await hub.enqueueAgentJob(projectId,String(b.kind||"assistant"),String(b.policy||"owner-approved"),input);await hub.setAgentJobRunning(job.id);try{const output=await executeAgent(provider,key,input);await hub.completeAgentJob(job.id,output);return json({jobId:job.id,status:"completed",output,provider:provider.name},201)}catch(e){const error=e instanceof Error?e.message:"agent_execution_failed";await hub.failAgentJob(job.id,error);return json({jobId:job.id,status:"failed",error},502)}}}
 if(parts[0]==="files"&&request.method==="GET"){const projectId=Number(url.searchParams.get("projectId")||0);if(!Number.isInteger(projectId)||!await hub.canAccessProject(user,projectId))return json({error:"project_access_denied"},403);return json({files:await hub.listFiles(projectId,url.searchParams.get("q")||"",url.searchParams.get("trash")==="1"?1:0)})}
 if(parts[0]==="files"||parts[0]==="shares"){if(user.role!=="OWNER")return json({error:"owner_required"},403);const id=Number(parts[1]);if(parts[0]==="files"&&parts[1]&&parts[2]==="rename"&&request.method==="POST"){const b=await body();await hub.renameFile(id,String(b.name||""));return json({ok:true})}if(parts[0]==="files"&&parts[1]&&parts[2]==="trash"&&request.method==="POST"){await hub.trashFile(id);return json({ok:true})}if(parts[0]==="files"&&parts[1]&&parts[2]==="restore"&&request.method==="POST"){await hub.restoreFile(id);return json({ok:true})}if(parts[0]==="shares"&&request.method==="GET")return json({shares:await hub.listShares(Number(url.searchParams.get("fileId"))||undefined)});if(parts[0]==="shares"&&request.method==="POST"){const b=await body();return json({share:await hub.createShare(Number(b.fileId),randomToken(),b.expiresAt?String(b.expiresAt):null)},201)}if(parts[0]==="shares"&&parts[1]&&parts[2]==="revoke"&&request.method==="POST"){await hub.revokeShare(id);return json({ok:true})}}
 if(parts[0]==="policy"&&request.method==="GET"){const p=await hub.getActiveAiProvider();return json({execution:p?"configured":"waiting_for_provider",codeExecution:false,production:true,defaultPolicy:"owner-approved"})}
 return json({error:"unknown_endpoint"},404)
}
export default{async fetch(request:Request,env:Env,ctx:ExecutionContext){const url=new URL(request.url);if(url.pathname.startsWith("/api/"))return api(request,env);if(env.ASSETS&&shouldServeAsset(request)){const r=await env.ASSETS.fetch(request);if(r.status!==404)return r}const hub=env.ITEMS.get(env.ITEMS.idFromName("hub")),user=await currentUser(request,hub),publicRoute=url.pathname==="/auth"||url.pathname.startsWith("/invite/");if(!publicRoute&&!user)return Response.redirect(new URL("/auth",url),302);if(url.pathname==="/"&&user?.role!=="OWNER")return Response.redirect(new URL(user?"/user":"/auth",url),302);if(url.pathname==="/user"&&user?.role!=="COLLABORATOR")return Response.redirect(new URL(user?.role==="OWNER"?"/":"/auth",url),302);return requestHandler(request,{cloudflare:{env,ctx,user}})}} satisfies ExportedHandler<Env>;
